name: tasty_and_easy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.7.1
  email_validator: ^2.1.17
  firebase_database: ^10.2.7
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  parallax: ^1.0.3
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.2.2

  # Add this line at the root level, aligned with flutter
  uuid: ^4.2.1
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/appbar_new.jpg
    - assets/ttt.jpg
    - assets/swipe.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"