name: tasty_and_easy
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  email_validator: ^2.1.17
  firebase_database: ^10.2.7
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  parallax: ^1.0.3
  # Add this line at the root level, aligned with flutter
  uuid: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/appbar_new.jpg
    - assets/ttt.jpg
    - assets/swipe.png
